### ISSUE TITLE
SortedMap should make use of covariant return types.

### ISSUE THREAD

**Issue by michaelamaura** [lacuna/bifurcan#10]
The following methods should have their return type adapted.

* `SortedMap#remove(K)` should return `SortedMap<K, V>`
* `SortedMap#put(K, V)` should return `SortedMap<K, V>`
* `SortedMap#put(K, V, BinaryOperator)` should return `SortedMap<K, V>`

Currently they always need to be re-casted to `(SortedMap(K, V))` which makes the code a bit ugly.

**Comment by ztellman** [comment]
Thanks, the library is due for a rev, so I’ll fix this and do a release.

**Comment by ztellman** [comment]
Fixed in `0.2.0-alpha1`
