### ISSUE TITLE
SortedMap should have the possibility to supply a custom `Comparator`

### ISSUE THREAD

**Issue by michaelamaura** [lacuna/bifurcan#11]
`SortedMap` already has a field `comparator`, but is is always set to `Comparator.naturalOrder()`.

There is also the private constructor `SortedMap(Node<K, V> root, boolean linear, Comparator<K> comparator)` that is used by `SortedMap` internally - although it can also be invoked with reflection magic. Tests show that it seems to work fine when supplying a custom `Comparator`.

But there should be an "official" possibility.

**Comment by ztellman** [comment]
fixed in `0.2.0-alpha1`
