### ISSUE TITLE
Do several methods mutate the internals of immutable List instances?

### ISSUE THREAD

**Issue by jafingerhut** [lacuna/bifurcan#16]
It appears that several methods like addLast, addFirst can cause method grow to be called, even if the List is documented as immutable, e.g. isLinear() returns false.

I agree that the code is mutating the node in such a way that smaller arrays are replaced with larger arrays that have the same contents in the indices that are common to both the old and new arrays, which is good.

The red flag it raises in my mind is that if thread T1 is executing grow on a forked List, and thread T2 is doing read-only operations on it concurrently, then modifications made by T1 might not be safely published to T2, and T2 could start getting inconsistent results for different array elements.

Does that sound possible?

**Comment by jafingerhut** [comment]
I believe that Clojure's PersistentVector avoids this issue by never mutating existing nodes, which have their references to child node arrays declared final, and instead doing path copying all the way up the tree to the root in cases like this.  The final declarations make the constructed nodes safely published to all other threads.

**Comment by jafingerhut** [comment]
I may have jumped to incorrect conclusions before creating this issue - I see that at least in some cases, grow may only be called on new nodes created from existing nodes in the tree.  If so, good.  I will keep looking for things that might not have full synchronization for inter-thread use of these data structures.

**Comment by ztellman** [comment]
Yes, in every case we call `grow` we've already called `clone` on all nodes which don't share our `editor`, making this safe.
