### ISSUE TITLE
No documentation about the maximum number of elements that can be stored in a List

### ISSUE THREAD

**Issue by JonathanVusich** [lacuna/bifurcan#22]
I recently tried to test the limits of the number of elements that can be stored in an instance of `List<Long>` and I learned (as I suspected) that indexing will not work properly with values that are greater than `Integer.MAX_VALUE`. This is because there is a downcast from `long` to `int` at line 79 of `List.java`. I think most users will assume that because `long` is used to index this collection that it will store more than `Integer.MAX_VALUE` number of elements. Some documentation to clarify this or to update the implementation to allow more values would be helpful. 😃

**Comment by ztellman** [comment]
Hi Jonathan,

Sorry for the slow response on this issue.  This is an artifact of earlier versions of the API, and at this point is probably close to a bug.  It is fixed in `0.2.0-alpha2`.
