### ISSUE TITLE
AIOOBE on List slice/concat usage

### ISSUE THREAD

**Issue by valich** [lacuna/bifurcan#25]
Hi! 

I have encountered a bug in List implementation when tried to implement Sorted Array data structure. I've been using concat and slice operations heavily to insert new elements at proper places, and it turned out my data structure failed after several iterations.

I've logged requests to List and recreated a pure test which fails with internal AIOOBE. Just in case, I've re-checked, the indices queried are correct and exist.

```
java.lang.ArrayIndexOutOfBoundsException: -1

	at io.lacuna.bifurcan.nodes.ListNodes$Node.pushLast(ListNodes.java:364)
	at io.lacuna.bifurcan.nodes.ListNodes.pushLast(ListNodes.java:34)
	at io.lacuna.bifurcan.nodes.ListNodes$Node.slice(ListNodes.java:240)
	at io.lacuna.bifurcan.List.slice(List.java:228)
	at io.lacuna.bifurcan.List.slice(List.java:19)
```

Here's the link to the gist: https://gist.github.com/valich/0958ed848ff5999532de59f360a2f899
I understand this is not a minimal sample, but I hope this will be enough to locate the problem. Please tell if you need more info.

The bug is present in 0.1.0 and 0.2.0-alpha.

Oh, yes, and removing linear/forked calls does not help either if that's important.

**Comment by valich** [comment]
It seems it's a duplicate for #19. Do you have any plans for publishing a new version to maven central?

**Comment by ztellman** [comment]
Hi, sorry to hear this bit you.  I'll push a release later today, and update the issue when it's available.

**Comment by ztellman** [comment]
I've just pushed `0.2.0-alpha2`, which should no longer have this issue.

**Comment by valich** [comment]
Awesome, thanks a lot! I've checked the release, it works for me well.
