### ISSUE TITLE
Use clojure.PersistentList instead of clojure.PersistentVector for list comparisons

### ISSUE THREAD

**Issue by jmromrell** [lacuna/bifurcan#5]
On the following page, you compare a number of persistent data structures:
https://github.com/lacuna/bifurcan/blob/master/doc/comparison.md

In the lists section, I think it would be more appropriate to use clojure.PersistentList than clojure.PersistentVector, considering you switch to the equivalent list types for other languages.

**Comment by ztellman** [comment]
I'm not sure why you'd think I'm not using vectors for all the other languages and libraries, it says "vector" in the name of the collections, except for Java and Bifurcan, which follow the Java naming convention of "list" not precluding random access.

**Comment by jmromrell** [comment]
The section heading and title of each graph all refer to lists rather than vectors. At least in clojure, that is a significant distinction which made it seem to me an unfair comparison was being made between list and vector types. I realize now that I overlooked that java's ArrayList was being used rather than LinkedList or an alternative.

Perhaps different different section heading and titles would have avoided this confusion and may be worth considering.
