### ISSUE TITLE
interpretor/compiler for bifurcan structures

### ISSUE THREAD

**Issue by hoebat** [lacuna/bifurcan#8]
It'll be really cool if there was a way for existing clojure code to be interpreted/compiled using bifurcan datastructures:

ie.
```
(assoc {} :a 1 :b 2) => io.lacuna.bifurcan.Map

(conj [] 1 2 3) => io.lacuna.bifurcan.List
```

I'm not too sure of the difficulty or the feasibility.

**Comment by ztellman** [comment]
This would require adding a Clojure-like facade to the data structures, and then forking Clojure.  I discussed the difficulties of the facades [a while ago](https://groups.google.com/forum/#!searchin/clojure/bifurcan%7Csort:date/clojure/1m_I7IrDGb0/0m_3rYnzAQAJ), and have no desire to fork Clojure.

**Comment by hoebat** [comment]
ah awesome. thanks for that.
